# Generated by Django 2.1.7 on 2019-04-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microbiome_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='kingdom',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='specie',
        ),
    ]
