# Generated by Django 2.1.7 on 2019-04-02 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microbiome_api', '0002_auto_20190402_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='kingdom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='microbiome_api.Kingdom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='specie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='microbiome_api.Specie'),
            preserve_default=False,
        ),
    ]
